limenius_react:
    default_rendering: "both"
    
    serverside_rendering:
        trace: true
        fail-loud: true
        mode: "phpexecjs"
        server_bundle_path: "%kernel.project_dir%/var/webpack/app.js"